proyecto/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

software/urls.py
from django.contrib import admin
from django.urls import path
from app import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("roles/", views.roles, name="roles"),
    path("roles/crear/", views.rol_crear, name="rol_crear"),
    path("roles/modificar/<int:rol_id>", views.rol_modificar, name="rol_modificar"),
    path("signout/", views.signout, name="signout"),
    path("signin/", views.signin, name="signin"),
    path("usuarios/", views.usuarios, name="usuarios"),
    path("usuarios/crear/", views.usuario_crear, name="usuario_crear"),
    path("usuarios/modificar/<int:usuario_id>/", views.usuario_modificar, name="usuario_modificar"),
    path("ingredientes/", views.ingredientes, name="ingredientes"),
    path("ingredientes/crear/", views.ingrediente_crear, name="ingrediente_crear"),
    path("ingredientes/modificar/<int:ingrediente_id>", views.ingrediente_modificar, name="ingrediente_modificar"),
    path("productos/", views.productos, name="productos"),
    path("productos/crear/", views.producto_crear, name="producto_crear"),
    path("productos/modificar/<int:producto_id>", views.producto_modificar, name="producto_modificar"),
    path('recetas/', views.recetas, name='recetas'),
    path('recetas/crear/', views.receta_crear, name='receta_crear'),
    path('recetas/modificar/<int:receta_id>/', views.receta_modificar, name='receta_modificar'),
    path('costos/', views.costos, name='costos'),
    path('costos/crear/', views.costo_crear, name='costo_crear'),
    path('ganancias/', views.ganancia, name='ganancias'),
    path('ganancia/crear/', views.ganancia_crear, name='ganancia_crear'),
    path('ganancia/modificar/<int:ganancia_id>/', views.ganancia_modificar, name='ganancia_modificar'),
    path('ventas/', views.ventas, name='ventas'),
    path('venta/crear/', views.venta_crear, name='venta_crear'),
    path('obtener_precio/',views.obtener_precio, name='obtener_precio'),
    path('clientes/', views.clientes, name='clientes'),
    path('clientes/crear/', views.cliente_crear, name='cliente_crear'),
    path('clientes/modificar/<int:cliente_id>/', views.cliente_modificar, name='cliente_modificar'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('transaccion/', views.transaccion, name='transaccion'),
    path('transaccion/crear/', views.transaccion_crear, name='transaccion_crear'),
    path('transaccion/modificar/<int:transaccion_id>/', views.transaccion_modificar, name='transaccion_modificar')
]

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone

# Create your models here.
class Rol(models.Model):
    id_rol = models.AutoField(primary_key=True)
    nombre_rol = models.CharField(max_length=50)
    descripcion = models.TextField(blank=True)
    estado = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    def __str__(self):
        return self.nombre_rol

class Usuario(AbstractUser):
    id = models.AutoField(primary_key=True)
    rol = models.ForeignKey(Rol, on_delete=models.CASCADE, null=True, blank=False)

    def __str__(self):
        return self.username

    @property
    def is_rol_admin(self):
        return self.rol.is_admin if self.rol else False

class UnidadesMedida(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Ingrediente(models.Model):
    id_ingrediente = models.AutoField(primary_key=True)
    nombre_ingrediente = models.CharField(max_length=100)
    cantidad = models.DecimalField(max_digits=10, decimal_places=2)
    unidad = models.CharField(max_length=10)
    precio_ingrediente = models.DecimalField(max_digits=10, decimal_places=2)
    estado_ingrediente = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre_ingrediente
    
    def clean(self):
        if self.precio_ingrediente < 0:
            raise ValidationError('El precio del ingrediente no puede ser negativo.')

class Producto(models.Model):
    id_producto = models.AutoField(primary_key=True)
    nombre_producto = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True, null=True)
    
    def __str__(self):
        return self.nombre_producto

class Receta(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    ingredientes = models.ManyToManyField(Ingrediente, through='RecetaIngrediente')

class RecetaIngrediente(models.Model):
    receta = models.ForeignKey(Receta, on_delete=models.CASCADE)
    ingrediente = models.ForeignKey(Ingrediente, on_delete=models.CASCADE)
    cantidad = models.DecimalField(max_digits=10, decimal_places=2)
    unidad = models.ForeignKey(UnidadesMedida, on_delete=models.CASCADE)

class CostoProducto(models.Model):
    id_costo = models.AutoField(primary_key=True)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    ingredientes = models.ManyToManyField(Ingrediente, through='CostoProductoIngrediente')
    costo_total = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    def __str__(self):
        return f"Costo de {self.producto.nombre_producto} - {self.costo_total if self.costo_total else 'No calculado'}"

    def calcular_costo_total(self):
        receta_ingredientes = RecetaIngrediente.objects.filter(receta__producto=self.producto)
        costo_total = sum(ri.cantidad * ri.ingrediente.precio_ingrediente for ri in receta_ingredientes)
        self.costo_total = costo_total
        self.save()

class CostoProductoIngrediente(models.Model):
    costo_producto = models.ForeignKey(CostoProducto, on_delete=models.CASCADE)
    ingrediente = models.ForeignKey(Ingrediente, on_delete=models.CASCADE)
    cantidad = models.DecimalField(max_digits=10, decimal_places=2)
    precio_ingrediente = models.DecimalField(max_digits=10, decimal_places=2)
    costo_total = models.DecimalField(max_digits=10, decimal_places=2)
    unidad = models.ForeignKey(UnidadesMedida, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.costo_producto.producto.nombre_producto} - {self.ingrediente.nombre_ingrediente}: {self.costo_total}"

class Ganancia(models.Model):
    id_ganancia = models.AutoField(primary_key=True)
    nombre_producto = models.CharField(max_length=100)
    costo_producto = models.DecimalField(max_digits=10, decimal_places=2)
    precio_con_ganancia = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'Ganancia para {self.nombre_producto}'

class Cliente(models.Model):
    id_cliente = models.AutoField(primary_key=True)
    nombre_cliente = models.CharField(max_length=100)
    correo_cliente = models.EmailField(blank=True, null=True)
    telefono_cliente = models.CharField(max_length=9,blank=True, null=True)
    def __str__(self):
        return self.nombre_cliente

class Venta(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True, blank=True)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    precio = models.DecimalField(max_digits=10, decimal_places=2, editable=False)
    fecha = models.DateField(auto_now_add=True)

    def save(self, *args, **kwargs):
        try:
            ganancia = Ganancia.objects.get(nombre_producto=self.producto.nombre_producto)
            self.precio = ganancia.precio_con_ganancia
        except Ganancia.DoesNotExist:
            self.precio = 0
        super().save(*args, **kwargs)
class Transaccion(models.Model):
    TIPO_TRANSACCION_CHOICES = [
        ('ingreso', 'Ingreso'),
        ('egreso', 'Egreso'),
    ]
    fecha = models.DateField(default=timezone.now)
    descripcion = models.TextField()
    tipo_transaccion = models.CharField(max_length=7, choices=TIPO_TRANSACCION_CHOICES)
    monto = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.fecha} - {self.descripcion} - {self.tipo_transaccion} - {self.monto}"

app/templates/transaccion/transaccion.html
{% extends 'layouts/base.html' %}

{% block content %}
<h1>Lista de Transacciones</h1>
<a class="btn btn-color fw-bold mb-3" href="{% url 'transaccion_crear' %}" role="button">Crear</a>
<table class="tb">
  <thead class="encabezado-tabla fw-bold">
    <tr>

        <td scope="col">Fecha</td>
        <td scope="col">Descripción</td>
        <td scope="col">Tipo de transacción</td>
        <td scope="col">Monto (S/.)</td>
        <th colspan="2">Opciones</th>
    </tr>
  </thead>
  <tbody class="bg-secondary-subtle">
    {% for transaccion in transacciones %}
    <tr>

        <td>{{ transaccion.fecha }}</td>
        <td>{{ transaccion.descripcion }}</td>
        <td>{{ transaccion.get_tipo_transaccion_display }}</td>
        <td>{{ transaccion.monto }}</td>
        <td>
            <a class="btn btn-color btn-m fw-bold" role="button" href="{% url 'transaccion_modificar' transaccion.id %}">
                <i class="bi bi-pencil-square"></i>
                Modificar
            </a>
        </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

app/templates/transaccion/transaccion_crear.html
{% extends 'layouts/base.html' %}

{% block content %}
  <h1>Crear Trasacción</h1>
  <div class="form card p-4" id="transaccion-form">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="d-flex gap-4">
            <button type="submit" class="btn btn-color">Registrar</button>
            <a href="{% url 'transaccion' %}" class="btn btn-dark">Cancelar</a>
        </div>
      </form>
  </div>
{% endblock %}

app/templates/transaccion/transaccion_modificar.html
{% extends 'layouts/base.html' %}

{% block content %}
  <h1>Modificar Transacción</h1>
  <div class="form card p-4">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="d-flex gap-4">
            <button type="submit" class="btn btn-color">Actualizar</button>
            <a href="{% url 'transaccion' %}" class="btn btn-dark">Cancelar</a>
        </div>
      </form>
  </div>
{% endblock %}